before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
upx:
  - enabled: true
    compress: "1"
archives:
  - format_overrides:
      - goos: windows
        format: zip
dockers:
  - image_templates:
    - "ghcr.io/devopshivehq/kustomize-generator-merger:latest"
    - "ghcr.io/devopshivehq/kustomize-generator-merger:{{ .Major }}"
    - "ghcr.io/devopshivehq/kustomize-generator-merger:{{ .Major }}.{{ .Minor }}"
    - "ghcr.io/devopshivehq/kustomize-generator-merger:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    build_flag_templates:
    - "--pull"
    # OCI annotations: https://github.com/opencontainers/image-spec/blob/main/annotations.md
    - "--label=org.opencontainers.image.created={{ .Date }}"
    - "--label=org.opencontainers.image.name={{ .ProjectName }}"
    - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    - "--label=org.opencontainers.image.version={{ .Version }}"
    - "--label=org.opencontainers.image.source={{ .GitURL }}"
release:
  github: {}
  name_template: "{{ .Version }}"
  prerelease: auto
  mode: append
signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - '--yes'
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
    artifacts: checksum
    output: true
docker_signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    args:
      - sign
      - '--yes'
      - '${artifact}'
    artifacts: all
    output: true
# Changelog is generated by release-please.
changelog:
  skip: true
