---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob01
spec:
  schedule: '0 1 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-app
            command:
            - echo
            - cronjob01
