name: Go - CI
on:
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: read

jobs:
  lint-and-test:
    name: Lint And Test Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
      with:
        go-version-file: go.mod
        cache: false
    - name: Run GolangCI linter
      uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86 # v6.1.0
      with:
        args: '--timeout=5m'
        skip-cache: true
        skip-save-cache: true
    - name: Run Go test coverage
      run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457 # v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Build Artifacts
    needs: ["lint-and-test"]
    permissions:
      id-token: write
      contents: write
      packages: write
      pull-requests: write
    uses: ./.github/workflows/tpl-packaging.yml
    secrets: inherit
    with:
      goreleaser-version: 2
      goreleaser-args: "release --clean --snapshot"
      artifacts-cache: true
      artifacts-cache-key: "dist-${{ github.run_id }}"
      artifacts-publish-ci: true
      artifacts-identifier: "${{ github.event.number == 0 && 'snapshot' || format('pr-{0}', github.event.number) }}"

  upload:
    name: Upload Artifacts - ${{ matrix.os.name }}
    needs: ["build"]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
        - name: Linux
          id: linux
        - name: MacOS
          id: darwin
        - name: Windows
          id: windows
    steps:
    - name: Get Cached Artifacts
      uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3
      with:
        path: dist
        key: dist-${{ github.run_id }}
    - run: find dist
    # The upload-artifact action doesn't support multi upload 🤷‍♂️!
    - name: Upload Artifacts - AMD
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
      with:
        name: merger-${{ matrix.os.id }}-amd
        path: |
          dist/kustomize-plugin-merger_*_${{ matrix.os.id }}_amd*
          dist/*checksums.txt*
    - name: Upload Artifacts - ARM
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
      with:
        name: merger-${{ matrix.os.id }}-arm
        path: |
          dist/kustomize-plugin-merger_*_${{ matrix.os.id }}_arm*
          dist/*checksums.txt*
