name: Go - Pre Release

on:
  push:
    branches:
    - main

permissions:
  contents: read

jobs:
  pre-release:
    name: Pre Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      packages: write
      pull-requests: write
    steps:
    - name: Run Release Please
      uses: GoogleCloudPlatform/release-please-action@4c5670f886fe259db4d11222f7dff41c1382304d # v3
      id: release
      with:
        release-type: go
        package-name: kustomize-plugin-merger
        changelog-types: |
          [
            {
              "type": "feat",
              "section": "Features",
              "hidden": false
            },
            {
              "type": "fix",
              "section": "Bug Fixes",
              "hidden": false
            },
            {
              "type": "docs",
              "section": "Documentation",
              "hidden": false
            },
            {
              "type": "ci",
              "section": "Continuous Integration",
              "hidden": false
            }
          ]
