name: Packaging

on:
  workflow_call:
    inputs:
      goreleaser-version:
        default: latest
        type: string
      goreleaser-args:
        required: true
        type: string
      registry-login:
        default: false
        type: boolean
      artifacts-cache:
        default: false
        type: boolean
      artifacts-cache-key:
        default: dist
        type: string
      artifacts-cache-path:
        default: dist
        type: string

permissions:
  contents: read

jobs:
  run:
    name: Run GoReleaser
    permissions:
      id-token: write
      contents: write
      packages: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
      with:
        go-version-file: go.mod
        cache: false
    - name: Setup Golang Caches
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Setup Cosign
      uses: sigstore/cosign-installer@main
    - name: Login to GitHub Container Registry
      if: ${{ inputs.registry-login }}
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup QEMU
      uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8 # v5
      with:
        version: "${{ inputs.goreleaser-version }}"
        args: "${{ inputs.goreleaser-args }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Cache Artifacts
      uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
      if: ${{ inputs.artifacts-cache }}
      with:
        path: "${{ inputs.artifacts-cache-path }}"
        key: "${{ inputs.artifacts-cache-key }}"
